executable('demo', 'demo.c', dependencies: abscom_dep)
executable('py_demo', 'py_demo.c', dependencies: abscom_dep)
executable('data_demo', 'data_demo.c', dependencies: abscom_dep)
executable('v6_demo', 'v6_demo.c', dependencies: abscom_dep)
executable('sci_demo', 'sci_demo.c', dependencies: abscom_dep)
executable('lang_demo', 'lang_demo.c', dependencies: abscom_dep)
executable('framework_demo', 'framework_demo.c', dependencies: abscom_dep)
executable('sort_demo', 'sort_demo.c', dependencies: abscom_dep)
